# Generated by Django 5.1.3 on 2024-11-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by_uid', models.CharField(max_length=255)),
                ('created_by_name', models.CharField(max_length=255)),
                ('assigned_to_uid', models.CharField(max_length=255)),
                ('assigned_to_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
